---
title: 'Energy Use and Economic Development Project: Preprocessing and Data Wrangling'
author: "Ben Holden & Lizzy MacIntosh"
date: '2022-02-10'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, include = FALSE}
suppressPackageStartupMessages(library(tidyverse))
```

## Part 1: Importing and merging datasets:

```{r import all datasets from GitHub, include = FALSE}

# world energy consumption dataset
wec <-  read_csv("https://github.com/ben-luc-hol/Energy-Use-Project/raw/main/data/world_energy_consumption.csv")

#CO2 emissions (metric tons per capita per year) - World Bank, 2022
co2_emissions <-  read_csv("https://github.com/ben-luc-hol/Energy-Use-Project/raw/main/data/CO2_emissions.csv")

#fertility
fertility <- read_csv("https://github.com/ben-luc-hol/Energy-Use-Project/raw/main/data/fertility_rate.csv")

#infant mortality
infant_mort <-  read_csv("https://github.com/ben-luc-hol/Energy-Use-Project/raw/main/data/infant_mortality.csv")

#life expectancy at birth
life_exp <-  read_csv("https://github.com/ben-luc-hol/Energy-Use-Project/raw/main/data/life_exp.csv")

#literacy
literacy <-  read_csv("https://github.com/ben-luc-hol/Energy-Use-Project/raw/main/data/literacy.csv")

#poverty
poverty <-  read_csv("https://github.com/ben-luc-hol/Energy-Use-Project/raw/main/data/poverty.csv")

```


### First, tidy and select variables from the main dataset used -- World Energy Consumption from Our World in Data
```{r tidy wec}
#glimpse(wec)

wec%>%
  select( #----- Key variables:  --------------------------------------------
          iso_code, #ISO country code
          country, #country
          year,    #year of observation
          population, #population total
          gdp, #  inflation-adjusted real GDP
          energy_per_gdp, # energy consumption per unit of GDP, kwh, 2011 dollars
          energy_per_capita, # Primary energy consumption per capita, kwh/year
          energy_cons_change_pct, #Annual pctage change in primary energy consumption	
#      ------------- Energy  -----------------------------------------------
          fossil_cons_change_pct, #Annual percentage change in fossil fuel consumption	
          fossil_share_energy, #Share of primary energy consumption that comes from fossil fuels	
          coal_share_energy, #Share of primary energy consumption that comes from coal	
          gas_share_energy, #Share of primary energy consumption that comes from gas	
          oil_share_energy, #	Share of primary energy consumption that comes from oil	
          low_carbon_cons_change_pct, #Annual percentage change in low-carbon energy consumption	
          hydro_share_energy,	#Share of primary energy consumption that comes from hydropower	
          solar_share_energy, #Share of electricity consumption that comes from solar	
          wind_share_energy, # Share of primary energy consumption that comes from wind	
          nuclear_share_energy, #Share of primary energy consumption that comes from other renewables	
          biofuel_share_energy, #Share of primary energy consumption that comes from biofuels	
          other_renewables_share_energy, #Share of primary energy consumption that comes from other renewables
          low_carbon_share_energy, #Share of primary energy consumption that comes from low-carbon sources (sum of primary energy from renewables and nuclear)		
#      ------------- Electricity -----------------------------------------------
          coal_share_elec, #Share of electricity consumption that comes from coal
          gas_share_elec, #Share of electricity consumption that comes from gas	
          oil_share_elec, #Share of electricity consumption that comes from oil	
          fossil_share_elec, #Share of electricity consumption that comes from fossil fuels (coal, oil and gas combined)	
          hydro_share_elec, #Share of electricity consumption that comes from hydropower	
          solar_share_elec, #Share of electricity consumption that comes from solar	
          wind_share_elec, #Share of electricity consumption that comes from wind	
          nuclear_share_elec, #Share of electricity consumption that comes from nuclear power	
          biofuel_share_elec, #Share of electricity consumption that comes from biofuels	
          other_renewables_share_elec_exc_biofuel,	#Share of electricity consumption that comes from other renewables excluding biofuels	
          low_carbon_share_elec #Share of electricity consumption that comes from low-carbon sources. This is the sum of electricity from renewables and nuclear		
        ) %>%
#      ------------- Computing additional economic variables: ----------------------------------------------
  mutate(gdp_per_capita = (gdp/population),
         gdp_per_capita_growth = (gdp_per_capita-lag(gdp_per_capita))/lag(gdp_per_capita))%>% #creating a GDP per capita variable
  relocate(gdp_per_capita, .before = energy_per_capita)%>% #relocating variables
  relocate(gdp_per_capita_growth, .after = gdp_per_capita)%>%
  filter(year >= 1960) -> wec_tidy

glimpse(wec_tidy)

```

### Then: Tidy and conform the other datasets to prepare for joins:

```{r tidy co2}
#glimpse(co2_emissions)

co2_emissions%>%
  pivot_longer(cols = `1960`:`2020`, names_to = "year", values_to = "co2_tons_per_capita")%>%
  select(`Country Code`, `Country Name`, year, co2_tons_per_capita)%>%
  rename(iso_code = `Country Code`,
         country = `Country Name`)%>%
  mutate(year = as.numeric(year)) -> co2_tidy

head(co2_tidy, 5)

```

```{r tidy fertility}
#glimpse(fertility)

fertility%>%
  pivot_longer(cols = `1960`:`2020`, names_to = "year", values_to = "fertility_rate")%>%
  select(`Country Code`, `Country Name`, year, fertility_rate)%>%
  rename(iso_code = `Country Code`,
         country = `Country Name`)%>%
    mutate(year = as.numeric(year)) -> fertility_tidy

  head(fertility_tidy, 5)
```
```{r tidy infant mortality}
#glimpse(infant_mort)

infant_mort%>%
  pivot_longer(cols = `1960`:`2020`, names_to = "year", values_to = "infant_mortality_rate")%>%
  select(`Country Code`, `Country Name`, year, infant_mortality_rate)%>%
  rename(iso_code = `Country Code`,
         country = `Country Name`)%>%
    mutate(year = as.numeric(year)) -> infant_mort_tidy

head(infant_mort_tidy, 5)
```
```{r tidy literacy}
#glimpse(literacy)

glimpse(literacy)%>%
  pivot_longer(cols = `1960`:`2020`, names_to = "year", values_to = "literacy_rate")%>%
  select(`Country Code`, `Country Name`, year, literacy_rate)%>%
  rename(iso_code = `Country Code`,
         country = `Country Name`)%>%
    mutate(year = as.numeric(year)) -> literacy_tidy

  head(literacy_tidy, 5)
```
```{r tidy life exp}
#glimpse(life_exp)

glimpse(life_exp)%>%
  pivot_longer(cols = `1960`:`2020`, names_to = "year", values_to = "life_expectancy")%>%
  select(`Country Code`, `Country Name`, year, life_expectancy)%>%
  rename(iso_code = `Country Code`,
         country = `Country Name`)%>%
    mutate(year = as.numeric(year)) -> life_exp_tidy

  head(life_exp_tidy, 5)
```


```{r tidy poverty}
#glimpse(poverty)

poverty%>%
  select(Entity, Code, Year, `$1.90 per day - share of population below poverty line`)%>%
  rename(poverty_rate_dollar_ninety = `$1.90 per day - share of population below poverty line`,
         year = Year,
         country = Entity,
         iso_code = Code) -> poverty_tidy

head(poverty_tidy, 5)
  

```

```{r monster merge}
wec_tidy%>%
  inner_join( co2_tidy, by = c("iso_code", "year", "country"))%>%
   inner_join(fertility_tidy, by = c("iso_code", "year", "country"))%>%
    inner_join(infant_mort_tidy, by = c("iso_code", "year", "country")) %>%
     inner_join(life_exp_tidy, by = c("iso_code", "year", "country"))%>%
      inner_join(literacy_tidy, by = c("iso_code", "year", "country")) -> master

glimpse(master)

```

```{r final tidy and write main df}
master%>%
  filter(year >= 1991)%>%
  inner_join(poverty_tidy, by = c("iso_code", "year", "country" ))%>%
  relocate((co2_tons_per_capita:poverty_rate_dollar_ninety), .before = gdp) -> World_Energy_Consumption_Main

write_csv(World_Energy_Consumption_Main, "data/World_Energy_Consumption_Main.csv")

```





## Part 2: Analysis

Research Question:



```{r}
ggplot(World_Energy_Consumption_Main, aes(gdp_per_capita, fossil_share_energy, color = ()))+
  geom_point()+
  geom_jitter()+
  geom_smooth(method = lm, se = FALSE)
```

```{r}
World_Energy_Consumption_Main%>%
  ggplot(aes(gdp_per_capita, energy_per_gdp))+
    geom_point()+
  geom_jitter()+
  geom_smooth(method = lm, se = FALSE)


```

```{r}
World_Energy_Consumption_Main%>%
  ggplot(aes(poverty_rate_dollar_ninety, low_carbon_share_energy))+
  geom_point()
```




```{r United States Electric Sources}
glimpse(World_Energy_Consumption_Main)
World_Energy_Consumption_Main%>%
  filter(year < 2019)%>%
  filter(country == "United States")%>%
  select(year, coal_share_elec , gas_share_elec, oil_share_elec, hydro_share_elec, solar_share_elec, wind_share_elec, nuclear_share_elec, 
  biofuel_share_elec,other_renewables_share_elec_exc_biofuel)%>%
  pivot_longer(cols = coal_share_elec:other_renewables_share_elec_exc_biofuel, names_to = "elec_source", values_to = "percent_of_elec")%>%
ggplot(aes(year, percent_of_elec, fill = elec_source))+
  geom_area(position = "stack")
  

    #  pivot_wider(names_from = "year", values_from = "percent_of_elec")%>%
```

